### ISSUE TITLE
Callback triggered when there is no change in clipboard 

### ISSUE THREAD

**Issue by TheColdVoid** [DoumanAsh/clipboard-master#4]
On MacOS, `master` will report a clipboard change when it starts, even if there is no clipboard change at that moment. This problem does not occur on Win or Linux platforms, only on MacOS.

**Comment by TheColdVoid** [comment]
I have fixed this issue,please review the pull request https://github.com/DoumanAsh/clipboard-master/pull/5

**Comment by DoumanAsh** [comment]
Fixed in 3.1.3
