### ISSUE TITLE
Async  Listener?

### ISSUE THREAD

**Issue by 0-don** [DoumanAsh/clipboard-master#7]
is it possible to make clipboard_change to async?

**Comment by DoumanAsh** [comment]
Because it is just callback, it is already technically speaking async.
You could simply send every event via channel in `on_clipboard_change` and `on_clipboard_error` and await for event from receiver end

**Comment by gnattu** [comment]
Unfortunately tokio does not like threads been non-async like this. From my testing, only the main thread is able to process the channel message sent from the monitor thread and if you want to sent the message across threads, other than main threads, the message never delivers unless the buffer is full and the channel is closed.

Let's look at this example:

```rust
async fn channel_proxy(mut rx: mpsc::Receiver<String>) {
    while let Some(message) = rx.recv().await {
        println!("Received: {}", message);
    }
}
#[tokio::main]
async fn main() {
    // Create a channel for communication
    let (tx, mut rx) = mpsc::channel::<String>(32);
    let (tx2, mut rx2) = mpsc::channel::<String>(32);

    let _ = tokio::spawn(monitor_clipboard(tx));
    let _ = tokio:: spawn(channel_proxy(rx));
    loop{}
```

There will be nothing sent to the proxy, but the monitor is running well.

If we change the code to let the rx in the main thread, then everything works:

```rust
#[tokio::main]
async fn main() {
    // Create a channel for communication
    let (tx, mut rx) = mpsc::channel::<String>(32);
    let (tx2, mut rx2) = mpsc::channel::<String>(32);

    let _ = tokio::spawn(monitor_clipboard(tx));
    while let Some(message) = rx.recv().await {
        println!("Received: {}", message);
    }
```

My educated guess would be that the non async loop in this lib prevents tokio's scheduler to schedule the receiver thread at all. More specifically, the `std::thread::sleep` call in `mac.rs`

**Comment by DoumanAsh** [comment]
@gnattu You should not spawn main loop of clipboard master on tokio runtime
Please create dedicated thread to run it.
Clipboard functionality is fully synchronous so it is impossible to have it integrated in tokio runtime as it is.
So your code should be something like that:

```rust
#[tokio::main]
async fn main() {
    // Create a channel for communication
    let (tx, mut rx) = mpsc::channel::<String>(32);
    let (tx2, mut rx2) = mpsc::channel::<String>(32);

    std::thread::spawn(move || {
        let handler = <YourHandlerType>::new(tx);
        clipboard_master::Master::new(handler).run();
    })
    let _ = tokio:: spawn(channel_proxy(rx));
    loop{}
}
```
